# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dskliarov/cpp_projects/cpp_algorithms

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dskliarov/cpp_projects/cpp_algorithms

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.5.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dskliarov/cpp_projects/cpp_algorithms/CMakeFiles /Users/dskliarov/cpp_projects/cpp_algorithms/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dskliarov/cpp_projects/cpp_algorithms/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cpp_algorithms

# Build rule for target.
cpp_algorithms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpp_algorithms
.PHONY : cpp_algorithms

# fast build rule for target.
cpp_algorithms/fast:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/build
.PHONY : cpp_algorithms/fast

src/array.o: src/array.cpp.o

.PHONY : src/array.o

# target to build an object file
src/array.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/array.cpp.o
.PHONY : src/array.cpp.o

src/array.i: src/array.cpp.i

.PHONY : src/array.i

# target to preprocess a source file
src/array.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/array.cpp.i
.PHONY : src/array.cpp.i

src/array.s: src/array.cpp.s

.PHONY : src/array.s

# target to generate assembly for a file
src/array.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/array.cpp.s
.PHONY : src/array.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/menu.o: src/menu.cpp.o

.PHONY : src/menu.o

# target to build an object file
src/menu.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/menu.cpp.o
.PHONY : src/menu.cpp.o

src/menu.i: src/menu.cpp.i

.PHONY : src/menu.i

# target to preprocess a source file
src/menu.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/menu.cpp.i
.PHONY : src/menu.cpp.i

src/menu.s: src/menu.cpp.s

.PHONY : src/menu.s

# target to generate assembly for a file
src/menu.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/menu.cpp.s
.PHONY : src/menu.cpp.s

src/sorting/quick_sort.o: src/sorting/quick_sort.cpp.o

.PHONY : src/sorting/quick_sort.o

# target to build an object file
src/sorting/quick_sort.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/sorting/quick_sort.cpp.o
.PHONY : src/sorting/quick_sort.cpp.o

src/sorting/quick_sort.i: src/sorting/quick_sort.cpp.i

.PHONY : src/sorting/quick_sort.i

# target to preprocess a source file
src/sorting/quick_sort.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/sorting/quick_sort.cpp.i
.PHONY : src/sorting/quick_sort.cpp.i

src/sorting/quick_sort.s: src/sorting/quick_sort.cpp.s

.PHONY : src/sorting/quick_sort.s

# target to generate assembly for a file
src/sorting/quick_sort.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/sorting/quick_sort.cpp.s
.PHONY : src/sorting/quick_sort.cpp.s

src/sorting/sort.o: src/sorting/sort.cpp.o

.PHONY : src/sorting/sort.o

# target to build an object file
src/sorting/sort.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/sorting/sort.cpp.o
.PHONY : src/sorting/sort.cpp.o

src/sorting/sort.i: src/sorting/sort.cpp.i

.PHONY : src/sorting/sort.i

# target to preprocess a source file
src/sorting/sort.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/sorting/sort.cpp.i
.PHONY : src/sorting/sort.cpp.i

src/sorting/sort.s: src/sorting/sort.cpp.s

.PHONY : src/sorting/sort.s

# target to generate assembly for a file
src/sorting/sort.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/sorting/sort.cpp.s
.PHONY : src/sorting/sort.cpp.s

src/utility.o: src/utility.cpp.o

.PHONY : src/utility.o

# target to build an object file
src/utility.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/utility.cpp.o
.PHONY : src/utility.cpp.o

src/utility.i: src/utility.cpp.i

.PHONY : src/utility.i

# target to preprocess a source file
src/utility.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/utility.cpp.i
.PHONY : src/utility.cpp.i

src/utility.s: src/utility.cpp.s

.PHONY : src/utility.s

# target to generate assembly for a file
src/utility.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_algorithms.dir/build.make CMakeFiles/cpp_algorithms.dir/src/utility.cpp.s
.PHONY : src/utility.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cpp_algorithms"
	@echo "... src/array.o"
	@echo "... src/array.i"
	@echo "... src/array.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/menu.o"
	@echo "... src/menu.i"
	@echo "... src/menu.s"
	@echo "... src/sorting/quick_sort.o"
	@echo "... src/sorting/quick_sort.i"
	@echo "... src/sorting/quick_sort.s"
	@echo "... src/sorting/sort.o"
	@echo "... src/sorting/sort.i"
	@echo "... src/sorting/sort.s"
	@echo "... src/utility.o"
	@echo "... src/utility.i"
	@echo "... src/utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

